# Generated by Django 5.2.1 on 2025-05-12 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True, verbose_name='Ngày hóa đơn')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Số hóa đơn')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền dịch vụ')),
                ('medicine_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền thuốc')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thuế')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng cộng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='medical_records.examination')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'user_type__in': ['STAFF', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Hóa đơn',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ ngân hàng'), ('TRANSFER', 'Chuyển khoản'), ('OTHER', 'Khác')], default='CASH', max_length=20, verbose_name='Phương thức thanh toán')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Số tham chiếu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('staff', models.ForeignKey(limit_choices_to={'user_type__in': ['STAFF', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-payment_date'],
            },
        ),
    ]
