# Generated by Django 5.2.1 on 2025-05-12 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả dịch vụ')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
            ],
            options={
                'verbose_name': 'Dịch vụ nha khoa',
                'verbose_name_plural': 'Dịch vụ nha khoa',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_date', models.DateField(verbose_name='Ngày khám')),
                ('diagnosis', models.TextField(verbose_name='Chẩn đoán')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Kế hoạch điều trị')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination', to='appointments.appointment')),
                ('dentist', models.ForeignKey(limit_choices_to={'user_type': 'DENTIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='performed_examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lần khám',
                'verbose_name_plural': 'Lần khám',
                'ordering': ['-examination_date'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá áp dụng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='medical_records.examination')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_services', to='medical_records.dentalservice')),
            ],
            options={
                'verbose_name': 'Dịch vụ đã sử dụng',
                'verbose_name_plural': 'Dịch vụ đã sử dụng',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú chung')),
                ('patient', models.OneToOneField(limit_choices_to={'user_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ bệnh án',
                'verbose_name_plural': 'Hồ sơ bệnh án',
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='medical_records.medicalrecord'),
        ),
    ]
