# Generated by Django 5.2.1 on 2025-05-12 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã thuốc')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thuốc')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('indication', models.TextField(blank=True, verbose_name='Chỉ định')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('expiry_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('stock_type', models.CharField(choices=[('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho'), ('ADJUST', 'Điều chỉnh')], max_length=10, verbose_name='Loại')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Mã tham chiếu')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name': 'Biến động kho thuốc',
                'verbose_name_plural': 'Biến động kho thuốc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(auto_now_add=True, verbose_name='Ngày kê đơn')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='medical_records.examination')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('dosage', models.CharField(max_length=255, verbose_name='Liều dùng')),
                ('instructions', models.TextField(verbose_name='Hướng dẫn sử dụng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá áp dụng')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='pharmacy.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn thuốc',
                'verbose_name_plural': 'Chi tiết đơn thuốc',
            },
        ),
    ]
